openapi: 3.0.0
info:
  title: WxO L4
  description: WxO L4 Services
  version: 0.1.0
servers:
  - url: https://wxo-l4-services.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
    /customers:
      get:
        tags:
          - Customers
        summary: L4 list of customers
        description: L4 list of customers
        operationId: l4_customers
        responses:
          '200':
            description: Customers with recent life events
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Customer_List'
          '422':
            description: Validation Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CreditRequest:
      properties:
        credit:
          type: number
          title: Credit
        rate:
          type: number
          title: Rate
      type: object
      required:
        - credit
        - rate
      title: CreditRequest
    CreditResponse:
      properties:
        monthly:
          type: number
          title: Monthly
        total:
          type: number
          title: Total
      type: object
      required:
        - monthly
        - total
      title: CreditResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    Customer:
      properties:
        name:
          type: string
          title: Name
        age:
          type: integer
          title: Age
        id:
          type: string
          title: Id
        email:
          type: string
          title: Email
        recent_change:
          type: string
          title: Recent Change
      type: object
      required:
        - name
        - age
        - id
        - email
        - recent_change
      title: Customer
    Customer_List:
      properties:
        totalSize:
          type: integer
          title: Totalsize
        records:
          items:
            $ref: '#/components/schemas/Customer'
          type: array
          title: Records
      type: object
      required:
        - totalSize
        - records
      title: Customer_List
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
