openapi: 3.0.0
info:
  title: WxO L4
  description: WxO L4 Services
  version: 0.1.0
servers:
  - url: https://wxo-l4-services.1d13bpwyy9q7.us-east.codeengine.appdomain.cloud
paths:
  /credit:
    post:
      summary: Credit calculator
      description: Calculates a monthly payment schedule.
      operationId: credit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    CreditRequest:
      properties:
        credit:
          type: number
          title: Credit
        rate:
          type: number
          title: Rate
      type: object
      required:
        - credit
        - rate
      title: CreditRequest
    CreditResponse:
      properties:
        monthly:
          type: number
          title: Monthly
        total:
          type: number
          title: Total
      type: object
      required:
        - monthly
        - total
      title: CreditResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
